; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c5-tft]
board = esp32-c5-devkitc-1
board_build.partitions = custom_8Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/ESP32-C5-tft>
build_flags =
	${env.build_flags}
	-Iboards/ESP32-C5-tft
	-Isrc
	-DDEVICE_NAME='"ESP32-C5"'
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCORE_DEBUG_LEVEL=1
	-fno-char8_t

	; IR
	-DIR_TX_PINS='{{"IR", 3}}'
	-DIR_RX_PINS='{{"IR", 7}}'
	-DTXLED=3
	-DLED_ON=HIGH
	-DLED_OFF=LOW

	; sd card - не используется
	-DSDCARD_CS=-1
	-DSDCARD_SCK=-1
	-DSDCARD_MISO=-1
	-DSDCARD_MOSI=-1

	; GPS
	-DGPS_SERIAL_TX=11
	-DGPS_SERIAL_RX=12

	; tft vars (ST7789 240x240, GMT130)
	-DROTATION=1
	-DBACKLIGHT=-1
	-DMINBRIGHT=160
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=240
	-DTFT_RGB_ORDER=TFT_BGR
	-DSMOOTH_FONT=1
	-DTFT_CS=-1
	-DTFT_DC=15
	-DTFT_RST=14
	-DTOUCH_CS=-1
	-DTFT_MOSI=7
	-DTFT_SCLK=6
	-DTFT_MISO=2
	-DTFT_BL=-1

	; text sizes
	-DFP=1
	-DFM=2
	-DFG=3
	; ui control buttons
	-DSEL_BTN=28
	-DUP_BTN=5
	-DDW_BTN=4
	-DBTN_ALIAS='"OK"'

	;FM Radio
	-DFM_SI4713=1 ;Uncomment to activate FM Radio using Adafruit Si4713

	; CC1101 SPI connection pins
	-DUSE_CC1101_VIA_SPI
	-DCC1101_GDO0_PIN=-1
	-DCC1101_SS_PIN=8
	-DCC1101_MOSI_PIN=SPI_MOSI_PIN
	-DCC1101_SCK_PIN=SPI_SCK_PIN
	-DCC1101_MISO_PIN=SPI_MISO_PIN

	; NRF24
	-DUSE_NRF24_VIA_SPI
	-DNRF24_CE_PIN=13
	-DNRF24_SS_PIN=9
	-DNRF24_MOSI_PIN=SPI_MOSI_PIN
	-DNRF24_SCK_PIN=SPI_SCK_PIN
	-DNRF24_MISO_PIN=SPI_MISO_PIN

	-DSPI_SCK_PIN=6
	-DSPI_MOSI_PIN=7
	-DSPI_MISO_PIN=2
	-DSPI_SS_PIN=-1

	; Ethernet W5500
	-DUSE_W5500_VIA_SPI
	-DW5500_SS_PIN=10
	-DW5500_MOSI_PIN=SPI_MOSI_PIN
	-DW5500_SCK_PIN=SPI_SCK_PIN
	-DW5500_MISO_PIN=SPI_MISO_PIN
	-DW5500_INT_PIN=-1
