; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c5-tft]
board = esp32-c5-devkitc-1
board_build.partitions = custom_8Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/ESP32-C5-tft>
custom_sdkconfig =
    CONFIG_SPIRAM=n
lib_ldf_mode = deep+
build_flags =
	${env.build_flags}
	-Iboards/ESP32-C5-tft
	-Isrc
	-I.pio/libdeps/esp32-c5-tft/ArduinoJson/src
    -I.pio/libdeps/esp32-c5-tft/SimpleCLI/src
    -I.pio/libdeps/esp32-c5-tft/NimBLE-Arduino/src
    -I.pio/libdeps/esp32-c5-tft/RF24
    -I.pio/libdeps/esp32-c5-tft/TinyGPSPlus/src
    -I.pio/libdeps/esp32-c5-tft/IRremoteESP8266/src
    -I.pio/libdeps/esp32-c5-tft/ESP32Time
    -I.pio/libdeps/esp32-c5-tft/JPEGDecoder
    -I.pio/libdeps/esp32-c5-tft/AnimatedGIF/src
    -I.pio/libdeps/esp32-c5-tft/PNGdec/src
    -I.pio/libdeps/esp32-c5-tft/RadioLib/src
    -I.pio/libdeps/esp32-c5-tft/FastLED/src
	-I.pio/libdeps/esp32-c5-tft/ESP32Time
    -I.pio/libdeps/esp32-c5-tft/NTPClient
    -I.pio/libdeps/esp32-c5-tft/Time
    -I.pio/libdeps/esp32-c5-tft/LibSSH-ESP32/src
    -I.pio/libdeps/esp32-c5-tft/Adafruit_BusIO
    -I.pio/libdeps/esp32-c5-tft/Adafruit_PN532
    -I.pio/libdeps/esp32-c5-tft/BER-TLV
    -I.pio/libdeps/esp32-c5-tft/Arduino_MFRC522v2/src
    -I.pio/libdeps/esp32-c5-tft/ESP-ChameleonUltra/src
    -I.pio/libdeps/esp32-c5-tft/ESP-Amiibolink/src
    -I.pio/libdeps/esp32-c5-tft/ESP-PN532BLE/src
    -I.pio/libdeps/esp32-c5-tft/ESP-PN532-UART/src
    -I.pio/libdeps/esp32-c5-tft/ESP-PN532Killer/src
    -I.pio/libdeps/esp32-c5-tft/FFT/src
    -I.pio/libdeps/esp32-c5-tft/WireGuard-ESP32-Arduino/src
    -I.pio/libdeps/esp32-c5-tft/OneWire
    -I.pio/libdeps/esp32-c5-tft/ESP32-PsRamFS/src
    -I.pio/libdeps/esp32-c5-tft/mquickjs/src
    -I.pio/libdeps/esp32-c5-tft/Adafruit_Si4713_Library
    -I.pio/libdeps/esp32-c5-tft/SmartRC-CC1101-Driver-Lib
    -I.pio/libdeps/esp32-c5-tft/ST25R3916-fork/src
    -I.pio/libdeps/esp32-c5-tft/NFC-RFAL-fork/src
    -I.pio/libdeps/esp32-c5-tft/ESPAsyncWebServer/src
    -I.pio/libdeps/esp32-c5-tft/AsyncTCP/src
	-Ilib/HAL
	-DDEVICE_NAME='"ESP32-C5"'
	-DESP32C5_DEVKITC_1_TFT=1
	;-DBOARD_HAS_PSRAM=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCORE_DEBUG_LEVEL=1
	-fno-char8_t

	; grove pins
	; defaults from https://github.com/espressif/arduino-esp32/blob/master/variants/esp32s3/pins_arduino.h
	-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	; text sizes
	-DFP=1
	-DFM=2
	-DFG=3
	; ui control buttons
	-DBTN_ALIAS='"OK"'

	;FM Radio
	-DFM_SI4713=1 ;Uncomment to activate FM Radio using Adafruit Si4713

